### PR TITLE
fix: Make BaseUIUnitTest extendable

### LINKED ISSUE #1660: Expose BaseUIUnitTest in order to be easier to extend
Currently UI Unit Test feature class hierarchy is as follows.: UIUnitTest and SpringUIUnitTest for JUnit 5 and UIUnit4Test and SpringUIUnit4Test for older JUnit versions. These classes are all "simple" classes that inherit from BaseUIUnitTest and add JUnit support. 

Now consider extending UI Unit Test to be used in non-JUnit framework, namely the TestNG. This would be straightforward to do if one could inherit in the same way from BaseUIUnitTest but this time use the TestNG annotations. This does not work because BaseUIUnitTest is package private.

### PR DESCRIPTION
**Pull request by TatuLund**
Fixes #1660

### CODE REVIEW

**Review by mshabarov — APPROVED** [review]

File: vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java [hunk 1]
```diff
@@ -143,7 +144,7 @@ protected void initVaadinEnvironment() {
         MockVaadin.setup(discoverRoutes(), MockedUI::new, lookupServices());
     }
 
-    void scanTesters() {
+    protected void scanTesters() {
```
Comment (mcollovati) [inline vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java:147]: Needs javadoc, as it is now exposed to end users

File: vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
Comment (mcollovati) [inline vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java:1]: Since we are making `BaseUIUnitTest` a public API, we should probably update the Javadoc to remove the `For internal use only` comment and to offered document the extension points (`initVaadinEnvironment`, `cleanVaadinEnvironment`, ...) and utility methods (`discoverRoutes`, `scandTesters`).

**Review by mcollovati — CHANGES_REQUESTED** [review]

File: vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
Comment (mcollovati) [reply vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java:1]: Thinking about `For internal use only`, it is maybe better to leave it there, as we are not suggesting to extend this class, and we should be free to change internals even with breaking changes.

**Review by mcollovati — APPROVED** [review]
