### PR TITLE
fix: add support for UploadHandler in UploadTester

### LINKED ISSUE #1970: JUnit-Testbench UploadTester can't handle UploadHandler
With the new UploadHandler interface (introduced in Vaadin 24.8) the UploadTester can't create a upload:
```
java.lang.IllegalStateException: Upload cannot be performed without a receiver set. Please firstly set the receiver implementation with upload.setReceiver

	at com.vaadin.flow.component.upload.Upload$DefaultStreamVariable.getOutputStream(Upload.java:898)
	at com.vaadin.flow.component.upload.UploadTester.doUpload(UploadTester.java:257)
	at com.vaadin.flow.component.upload.UploadTester.lambda$doUpload$5(UploadTester.java:215)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.vaadin.flow.component.upload.UploadTester.doUpload(UploadTester.java:218)
	at com.vaadin.flow.component.upload.UploadTester.upload(UploadTester.java:102)
```
Please provide a method using the UploadHandler.
Vaadin version 24.8.3 is used in our project.

### PR DESCRIPTION
**Pull request by mcollovati**
Fixes #1970

### CODE REVIEW

File: vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/upload/UploadTesterTest.java [hunk 1]
```diff
@@ -79,177 +82,78 @@ void upload_notUsable_throws() {
...
-        Assertions.assertFalse(failed.get(), "Failed listener was notified");
-        Assertions.assertTrue(finished.get(),
-                "Finished listener was not notified");
+        listener.assertStarted();
+        listener.assertProgressCalled();
+        listener.assertCompleted();
+        listener.assertNotFailed();
         Assertions.assertTrue(allFinished.get(),
                 "All Finished listener was not notified");
+        Assertions.assertTrue(allFinished.get(),
```
Comment (tltv) [inline vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/upload/UploadTesterTest.java:100]: `allFinished.get()` is already asserted above.

Comment (mcollovati) [reply vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/upload/UploadTesterTest.java:100]: Good catch, thanks!

**Review by tltv — APPROVED** [review]
