### PR TITLE
fix: make MenuAccessControl availalble in mocking environment

### LINKED ISSUE #1844: UI Unit test navigation fails if frontend routes are present
Running a UI Unit test having with an existing `file-routes.json` file in the `generated` folder may fail because `MenuAccessControl` is not provided in the mock Vaadin environment

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.vaadin.flow.server.auth.MenuAccessControl': Failed to instantiate [com.vaadin.flow.server.auth.MenuAccessControl]: Specified class is an interface

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1339)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1224)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:322)
	at com.vaadin.flow.spring.SpringInstantiator.getOrCreate(SpringInstantiator.java:155)
	at com.vaadin.testbench.unit.mocks.MockInstantiator.getOrCreate(MockInstantiator.kt:31)
	at com.vaadin.flow.di.Instantiator.getMenuAccessControl(Instantiator.java:217)
	at com.vaadin.flow.internal.menu.MenuRegistry.filterClientViews(MenuRegistry.java:492)
	at com.vaadin.flow.internal.menu.MenuRegistry.collectClientMenuItems(MenuRegistry.java:331)
	at com.vaadin.flow.internal.menu.MenuRegistry.collectClientMenuItems(MenuRegistry.java:286)
	at com.vaadin.flow.internal.menu.MenuRegistry.getClientRoutes(MenuRegistry.java:594)
	at com.vaadin.flow.internal.menu.MenuRegistry.hasClientRoute(MenuRegistry.java:577)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.isClientHandled(AbstractNavigationStateRenderer.java:358)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:179)
	at com.vaadin.flow.router.internal.ErrorStateRenderer.handle(ErrorStateRenderer.java:106)
	at com.vaadin.flow.component.UI.handleExceptionNavigation(UI.java:2082)
	at com.vaadin.flow.component.UI.handleNavigation(UI.java:2057)
	at com.vaadin.flow.component.UI.renderViewForRoute(UI.java:2012)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.vaadin.testbench.unit.mocks.MockedUI.navigate(MockedUI.kt:46)
	at com.vaadin.flow.component.UI.navigate(UI.java:1188)
	at com.vaadin.flow.component.UI.navigate(UI.java:1001)
	at com.vaadin.flow.component.UI.navigate(UI.java:913)
	at com.vaadin.testbench.unit.BaseUIUnitTest.navigate(BaseUIUnitTest.java:227)
```

To reproduce
* add a frontend view to a Vaadin project with frontend hot deploy enabled
* start the application and make sure `file-routes.json` is created
* add and run a simple UI Unit Test; it should fail with an exception similar to the reported one
   ```java
   @ViewPackages
   public class MyTest extends SpringUIUnitTest {
     @Test
     void testMe() {
        navigate(MyView.class);
        Assertions.assertTrue(true);
     }
   ```

### PR DESCRIPTION
**Pull request by mcollovati**
Fixes #1844

### CODE REVIEW

**Comment by mcollovati** [comment]
Tested on internal CI against 24.5, 24.6 and 24.7

File: vaadin-testbench-unit-junit5/src/test/java/com/vaadin/testbench/unit/SecurityTestConfig.java [hunk 1]
```diff
@@ -88,5 +90,32 @@ public UserDetails loadUserByUsername(String username)
                 }
             };
         }
+
+        @Bean
+        MenuAccessControl menuAccessControl() {
+            // Workaround to support both Vaadin 24.4 that does not have
+            // SpringMenuAccessControl
```
Comment (tepi) [inline vaadin-testbench-unit-junit5/src/test/java/com/vaadin/testbench/unit/SecurityTestConfig.java:97]: Maybe something is missing in this comment, did it mean to mention another vaadin version as well?

Comment (mcollovati) [reply vaadin-testbench-unit-junit5/src/test/java/com/vaadin/testbench/unit/SecurityTestConfig.java:97]: You're right, the comment is incomplete.
`SpringMenuAccessControl` has been introduced in Vaadin 24.5, but Testbench main is currently 24.4+

Comment (mcollovati) [reply vaadin-testbench-unit-junit5/src/test/java/com/vaadin/testbench/unit/SecurityTestConfig.java]: updated comment

**Review by tepi — APPROVED** [review]
